# Generated by Zebra: Sensor Calibration
# Upload target: :/robot/color_calibration.py
COLOR_CALIBRATIONS = {
    6: [
        {"color": "blue", "rgb": {"r": 301, "g": 317, "b": 312, "clear": 905}, "normalized": {"r": 323, "g": 340, "b": 335}},
        {"color": "green", "rgb": {"r": 400, "g": 455, "b": 334, "clear": 1093}, "normalized": {"r": 336, "g": 382, "b": 280}},
        {"color": "brown", "rgb": {"r": 380, "g": 357, "b": 308, "clear": 977}, "normalized": {"r": 363, "g": 341, "b": 294}},
        {"color": "red", "rgb": {"r": 528, "g": 327, "b": 278, "clear": 1091}, "normalized": {"r": 466, "g": 288, "b": 245}},
        {"color": "pink", "rgb": {"r": 527, "g": 415, "b": 392, "clear": 1300}, "normalized": {"r": 395, "g": 311, "b": 293}},
        {"color": "purple", "rgb": {"r": 403, "g": 382, "b": 369, "clear": 1087}, "normalized": {"r": 349, "g": 331, "b": 319}},
    ],
}
